apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-netflix
  labels:
    app: azure-netflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-netflix
  template:
    metadata:
      labels:
        app: azure-netflix
    spec:
      containers:
      - name: azure-netflix
        image: pirateemperor.azurecr.io/netflix:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: azure-netflix
  labels:
    app: azure-netflix
spec:
  # type: NodePort
  # ports:
  # - port: 80
  #   targetPort: 80
  #   nodePort: 30007
  # selector:
  #   app: azure-netflix
  selector:
    app: azure-netflix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 