apiVersion: v1
kind: Service
metadata:
  name: azure-netflix
  labels:
    app: azure-netflix
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: azure-netflix
